In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.96553462,  1.03744715,  0.34228976, -0.19293972,  1.43123582,
        0.44529054, -0.94946633, -0.05143043, -0.25651619, -1.62995533])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([ -7.55633039e-01,  -9.76861642e-01,   1.14441380e+00,
        -7.85787032e-01,   8.57103473e-01,  -6.51139477e-02,
         9.08448952e-01,   2.29692401e-01,  -6.18142630e-01,
        -2.24968315e-04])

In [10]:
np.add(A,B)

array([ 0.20990158,  0.06058551,  1.48670356, -0.97872675,  2.2883393 ,
        0.38017659, -0.04101737,  0.17826197, -0.87465882, -1.6301803 ])

In [11]:
np.maximum(A,B)

array([  9.65534619e-01,   1.03744715e+00,   1.14441380e+00,
        -1.92939722e-01,   1.43123582e+00,   4.45290540e-01,
         9.08448952e-01,   2.29692401e-01,  -2.56516190e-01,
        -2.24968315e-04])

In [12]:
A

array([ 0.96553462,  1.03744715,  0.34228976, -0.19293972,  1.43123582,
        0.44529054, -0.94946633, -0.05143043, -0.25651619, -1.62995533])