In [7]:
import pandas as pd
import numpy as np
from pandas import Series
from pandas import DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ser1 = Series([0, 1, 2], index=['T', 'U', 'V'])
ser2 = Series([3,4], index=['X', 'Y'])

In [10]:
ser1

T    0
U    1
V    2
dtype: int64

In [11]:
ser2

X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1, ser2, ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [14]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [15]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
pd.concat([ser1, ser2], axis=1, keys=['cat1', 'cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [26]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])

In [27]:
dframe1

X         Y         Z
0 -0.909026 -0.972764 -0.435475
1  0.254182 -0.468654 -0.367580
2 -1.092444 -0.174728 -0.846500
3  1.099581  0.120983 -2.142965

In [28]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'X'])

In [29]:
dframe2

Y         Q         X
0  1.830219 -0.353062 -0.881372
1 -1.542927  0.794221 -0.502949
2  0.796097  2.027966  0.640805

In [30]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN -0.909026 -0.972764 -0.435475
1       NaN  0.254182 -0.468654 -0.367580
2       NaN -1.092444 -0.174728 -0.846500
3       NaN  1.099581  0.120983 -2.142965
0 -0.353062 -0.881372  1.830219       NaN
1  0.794221 -0.502949 -1.542927       NaN
2  2.027966  0.640805  0.796097       NaN

In [31]:
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.909026 -0.972764 -0.435475
1       NaN  0.254182 -0.468654 -0.367580
2       NaN -1.092444 -0.174728 -0.846500
3       NaN  1.099581  0.120983 -2.142965
4 -0.353062 -0.881372  1.830219       NaN
5  0.794221 -0.502949 -1.542927       NaN
6  2.027966  0.640805  0.796097       NaN